

#define NMPRK_SUCCESS						0
#define NMPRK_FAILURE						-1
#define NMPRK_INVALID_HANDLE				-2
#define NMPRK_INVALID_DATA_LENGTH			-3
#define NMPRK_NOT_FOUND						-4
#define NMPRK_PROXY_ERROR					-5
#define NMPRK_PROXY_ERROR_XFER				-6
#define NMPRK_PROXY_ERROR_NO_RSP			-7
#define NMPRK_PROXY_ERROR_INVALID_RSP		-8
#define NMPRK_PROXY_ERROR_INVALID_ASYNC_RSP	-9
#define NMPRK_INVALID_ARGUMENT				-10
#define NMPRK_INVALID_RSP_LENGTH			-11
#define NMPRK_DRIVER_ERROR					-12